name: word_search
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.1.0
  flutter_image_compress: ^2.3.0
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  onnxruntime: 
    git:
      url: https://github.com/Somespi/onnxruntime_flutter.git
      ref: 526de65
  opencv_dart: ^1.3.3
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/letter_recognition_model.onnx